jobs:
  - job: x_test
    variables:
      - name: IMAGE_NAME
        value: ubuntu-18.04
      - group: certbot-common
    strategy:
      matrix:
        nginx-compat:
          TOXENV: nginx_compat
        le-auto-jessie:
          TOXENV: le_auto_jessie
        le-auto-centos6:
          TOXENV: le_auto_centos6
        le-auto-oraclelinux6:
          TOXENV: le_auto_oraclelinux6
        dev:
          TOXENV: docker_dev
    pool:
      vmImage: $(IMAGE_NAME)
    steps:
      - template: ../steps/tox-steps.yml
