jobs:
  - job: test
    strategy:
      matrix:
        apache-compat:
          IMAGE_NAME: ubuntu-18.04
          TOXENV: apache_compat
        le-auto-xenial:
          IMAGE_NAME: ubuntu-18.04
          TOXENV: le_auto_xenial
        apacheconftest:
          IMAGE_NAME: ubuntu-18.04
          PYTHON_VERSION: 2.7
          TOXENV: apacheconftest-with-pebble
        nginxroundtrip:
          IMAGE_NAME: ubuntu-18.04
          PYTHON_VERSION: 2.7
          TOXENV: nginxroundtrip
    pool:
      vmImage: $(IMAGE_NAME)
    steps:
      - template: ../steps/tox-steps.yml
